cache:
  directories:
    - node_modules
    - example/node_modules

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_SDK_ROOT=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - QEMU_AUDIO_DRV=none
    - secure: hatwqC4bsfDLFU45N5bLhC8W0nxzXo2aH+HSvGKi1hjzwGgm+gjpJyrm1D45S7xJbgtrHkhOm6He4JqFz/kEgW2BfhIq4zHBO8fUUfOzG91lGNk9tvqlOY7FMQOLJL0bIAFsoy3E3ZWhdE4XJOSkvrQVVKA+IH9gDrfyV+9mkA3sgnKIT1Sa589Ty2p6nxbCsTLVyhHT2U1PXnasAa37rrD+jL78GbgoQHY6/2RGKJQIEfB6fgjSSxduft+1o7bC+bpWoSdQBDiWHYfw+7OIvBG64Cpnps5DTjBdnbKGPiFvTZ5pNRD3Q1bdvkF3HGRC4Oss9BeKm1oNx+3AceWHr/qA/LSuSk3M+rEbu7UkigAmILhDvzf10FZgoPC/IdPdwiXDAvpBDYA0CNz9+FwaWwtzncqndOQcj797kwDJ6JUGBpBkQWW9lpNSzxerygNNdmG2QmNEk8xOUPRht2aufc+0pPl/ZY9PUIW11IChvSrq5hqMmd/PIvO3mwf7zVj58ddBy5vFAakFuJrAUB0KD4dKW2NHkKFIwIvIs2NXHFhTJNSQxSs+qTN4vSGTKcPZfH0+eT0/kE6bQ5OnDkZryIbyW+7GTI/56R3EMuu+o5OE762S8G4gN2SwrqGxlxAVUdh3oltBLlfh73fiFdZDny+Nc3ABWC2QHFvAaT8Qor4=

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "10"

      before_install:
        - npm install -g yarn
      script:
        - yarn ci

    - stage: build
      name: "Build Android"
      language: android
      dist: trusty
      android:
        components:
          - tools
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
        - yes | sdkmanager "platform-tools" >/dev/null
        - yes | sdkmanager "tools" >/dev/null # A second time per Travis docs, gets latest versions
        - yes | sdkmanager "build-tools;28.0.3" >/dev/null # Implicit gradle dependency - gradle drives changes
        - yes | sdkmanager "platforms;android-28" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
        - yes | sdkmanager "extras;android;m2repository" >/dev/null
        - yes | sdkmanager "emulator"
        - yes | sdkmanager "system-images;android-25;google_apis;x86_64" >/dev/null
        - avdmanager create avd --force -n "TestingAVD" -k "system-images;android-25;google_apis;x86_64"  -g "google_apis" -d "Nexus 4"
        - emulator -verbose -avd TestingAVD -no-accel -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &
        - nvm install 10
        - node --version
        - npm install -g yarn
        - yarn -version
        - cd example
        - yarn
      script:
        - yarn detox build -c android.emu.release
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
        - yarn detox test -c android.emu.release -l verbose -u

    - stage: build
      name: "Build iOS"
      language: objective-c
      os: osx
      osx_image: xcode11.6
      before_install:
        - nvm install 10
        - node --version
        - npm install -g yarn
        - yarn -version
        - cd example
        - yarn
        - gem install cocoapods
        - cd ios && pod install --repo-update && cd ..
        - softwareupdate --list
        - softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"
        - brew tap wix/brew
        - brew install applesimutils
        - yarn global add react-native-cli
        - yarn detox clean-framework-cache &&  yarn detox build-framework-cache
        - xcrun simctl boot "iPhone 5s" || true
      script:
        - yarn detox build -c ios.sim.release
        - yarn detox test -c ios.sim.release -l verbose -u

    - stage: deploy
      name: "Publish to npm"
      language: node_js
      node_js:
        - "10"
      before_install:
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/.npmrc
      script:
        - npm publish
      if: tag =~ ^v
