version: 2.1

orbs:
  rn: react-native-community/react-native@4.4.2

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Jest
          command: yarn run test

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          on_after_initialize: "cd example && yarn install --frozen-lockfile --non-interactive --cache-folder /tmp/yarn && cd .."
          requires:
            - analyse
      - rn/android_build:
          name: build_android_release
          project_path: "example/android"
          build_type: release
          on_after_initialize: "cd example && yarn install --frozen-lockfile --non-interactive --cache-folder /tmp/yarn && cd .."
          requires:
            - analyse
      - rn/android_test:
          detox_configuration: "android.emu.release"
          detox_loglevel: "trace"
          requires:
            - build_android_release
